MetricasStatus = {
    'Dívida Líquida/EBIT': {
        'pessimo': {'min': 4, 'max': float('inf')},
        'ruim': {'min': 3, 'max': 4},
        'moderado': {'min': 1.5, 'max': 3},
        'bom': {'min': 0, 'max': 1.5},
        'otimo': {'min': float('-inf'), 'max': 0},
        'descricao': 'Relação entre dívida líquida e EBIT. Valores altos indicam maior alavancagem e risco financeiro.',
        'agrupador': 'Endividamento',
        'descrpessimo': 'Endividamento crítico, leva mais de 4 anos de EBIT para quitar a dívida líquida, indicando alavancagem extrema e risco financeiro elevado. Comum em empresas em crise (ex.: OIBR3) ou setores cíclicos em baixa (ex.: CSNA3). Em 2025, com juros de 10-12%, o custo da dívida pressiona a geração de caixa, aumentando a vulnerabilidade a choques econômicos. Evitar, salvo sinais claros de recuperação.',
        'descrruim': 'Endividamento elevado, 3-4 anos de EBIT. Risco significativo, especialmente em setores cíclicos (ex.: VALE3). Em 2025, verificar estabilidade do EBIT e plano de desalavancagem.',
        'descrmoderado': 'Endividamento moderado, 1,5-3 anos de EBIT. Aceitável em setores estáveis (ex.: ENGI11). Em 2025, monitorar fluxo de caixa livre e riscos macroeconômicos.',
        'descrbom': 'Endividamento baixo, até 1,5 anos de EBIT. Sólido, comum em setores maduros (ex.: ITUB4). Atraente para investidores conservadores.',
        'descotimo': 'Dívida líquida negativa, caixa excede dívidas. Situação excepcional, comum em tecnologia (ex.: WEGR3). Em 2025, avaliar alocação de caixa.'
    },
    'Dívida Líquida/EBITDA': {
        'pessimo': {'min': 3.5, 'max': float('inf')},
        'ruim': {'min': 2.5, 'max': 3.5},
        'moderado': {'min': 1, 'max': 2.5},
        'bom': {'min': 0, 'max': 1},
        'otimo': {'min': float('-inf'), 'max': 0},
        'descricao': 'Relação entre dívida líquida e EBITDA. Valores altos indicam alavancagem elevada.',
        'agrupador': 'Endividamento',
        'descrpessimo': 'Endividamento crítico, >3,5x o EBITDA. Alto risco de default, comum em empresas em crise (ex.: OIBR3). Em 2025, com juros de 10-12%, evitar salvo recuperação clara.',
        'descrruim': 'Endividamento elevado, 2,5-3,5x o EBITDA. Risco em setores cíclicos (ex.: CSNA3). Verificar plano de redução de dívida.',
        'descrmoderado': 'Endividamento moderado, 1-2,5x o EBITDA. Aceitável em setores estáveis (ex.: EGIE3). Monitorar fluxo de caixa em 2025.',
        'descrbom': 'Endividamento baixo, até 1x o EBITDA. Sólido, comum em bens de consumo (ex.: ABEV3). Atraente para conservadores.',
        'descotimo': 'Dívida líquida negativa, caixa supera dívidas. Excelente, comum em tecnologia (ex.: WEGR3). Avaliar uso do caixa.'
    },
    'Dívida Líquida/Patrimônio Líquido': {
        'pessimo': {'min': 1, 'max': float('inf')},
        'ruim': {'min': 0.7, 'max': 1},
        'moderado': {'min': 0.3, 'max': 0.7},
        'bom': {'min': 0, 'max': 0.3},
        'otimo': {'min': float('-inf'), 'max': 0},
        'descricao': 'Relação entre dívida líquida e patrimônio líquido. Indica alavancagem em relação ao capital próprio.',
        'agrupador': 'Endividamento',
        'descrpessimo': 'Alavancagem crítica, dívida excede PL (ex.: OIBR3). Alto risco de insolvência em 2025. Evitar.',
        'descrruim': 'Alavancagem elevada, 70-100% do PL (ex.: CSNA3). Cautela, verificar solvência.',
        'descrmoderado': 'Alavancagem moderada, 30-70% do PL (ex.: ENGI11). Monitorar ROE e fluxo de caixa.',
        'descrbom': 'Baixa alavancagem, até 30% do PL (ex.: ITUB4). Atraente para conservadores.',
        'descotimo': 'Caixa excede dívida, situação robusta (ex.: WEGR3). Avaliar alocação de capital.'
    },
    'Patrimônio/Ativos': {
        'pessimo': {'min': float('-inf'), 'max': 0.2},
        'ruim': {'min': 0.2, 'max': 0.3},
        'moderado': {'min': 0.3, 'max': 0.5},
        'bom': {'min': 0.5, 'max': 0.7},
        'otimo': {'min': 0.7, 'max': float('inf')},
        'descricao': 'Proporção do patrimônio em relação aos ativos totais. Indica robustez financeira.',
        'agrupador': 'Endividamento',
        'descrpessimo': 'Estrutura frágil, patrimônio <20% dos ativos ou negativo (ex.: OIBR3). Alto risco de insolvência. Evitar.',
        'descrruim': 'Estrutura limitada, 20-30% dos ativos (ex.: CSNA3). Cautela, verificar solvência.',
        'descrmoderado': 'Estrutura equilibrada, 30-50% dos ativos (ex.: ENGI11). Seguro com boa gestão.',
        'descrbom': 'Estrutura forte, 50-70% dos ativos (ex.: ABEV3). Atraente para conservadores.',
        'descotimo': 'Estrutura robusta, >70% dos ativos (ex.: WEGR3). Excelente, verificar alocação.'
    },
    'PL/Ativos': {
        'pessimo': {'min': float('-inf'), 'max': 0.2},
        'ruim': {'min': 0.2, 'max': 0.3},
        'moderado': {'min': 0.3, 'max': 0.5},
        'bom': {'min': 0.5, 'max': 0.7},
        'otimo': {'min': 0.7, 'max': float('inf')},
        'descricao': 'Relação entre patrimônio líquido e ativos totais. Indica solidez financeira.',
        'agrupador': 'Endividamento',
        'descrpessimo': 'Patrimônio muito baixo ou negativo, <20% dos ativos (ex.: OIBR3). Evitar.',
        'descrruim': 'Patrimônio limitado, 20-30% (ex.: CSNA3). Cautela.',
        'descrmoderado': 'Patrimônio equilibrado, 30-50% (ex.: ENGI11). Seguro.',
        'descrbom': 'Patrimônio forte, 50-70% (ex.: ABEV3). Atraente.',
        'descotimo': 'Patrimônio robusto, >70% (ex.: WEGR3). Excelente.'
    },
    'Dividend Yield (DY)': {
        'pessimo': {'min': 0, 'max': 0},
        'ruim': {'min': 0.1, 'max': 2},
        'moderado': {'min': 2, 'max': 4},
        'bom': {'min': 4, 'max': 6},
        'otimo': {'min': 6, 'max': float('inf')},
        'descricao': 'Rendimento de dividendos. Acima de 6% é considerado bom.',
        'agrupador': 'Renda',
        'descrpessimo': 'Sem dividendos, foco em reinvestimento ou prejuízo (ex.: startups). Evitar para renda.',
        'descrruim': 'Dividendos baixos, 0,1-2% (ex.: MGLU3). Pouco atrativo para renda.',
        'descrmoderado': 'Dividendos moderados, 2-4% (ex.: ENGI11). Equilíbrio entre renda e reinvestimento.',
        'descrbom': 'Dividendos atrativos, 4-6% (ex.: ITUB4). Ideal para renda.',
        'descotimo': 'Dividendos altos, >6% (ex.: TAEE11). Verificar sustentabilidade.'
    },
    'EV/EBIT': {
        'pessimo': [
            {'min': float('-inf'), 'max': 0, 'condicao': 'EBIT negativo'},
            {'min': 20, 'max': float('inf'), 'condicao': 'Valuation elevado'}
        ],
        'ruim': {'min': 15, 'max': 20},
        'moderado': {'min': 10, 'max': 15},
        'bom': {'min': 5, 'max': 10},
        'otimo': {'min': float('-inf'), 'max': 5, 'condicao': 'EV negativo com EBIT positivo ou baixo múltiplo'},
        'descricao': 'Relação entre valor da empresa e EBIT. Valores muito baixos ou negativos (EV negativo com EBIT positivo) sugerem subvalorização.',
        'agrupador': 'Valuation',
        'descrpessimo': 'Valuation elevado (>20x, ex.: startups tech) ou EBIT negativo (ex.: OIBR3). Alto risco de supervalorização ou prejuízo operacional. Em 2025, com juros de 10-12%, evitar salvo crescimento excepcional do EBIT.',
        'descrruim': 'Valuation alto, 15-20x (ex.: MGLU3). Cautela, verificar consistência do EBIT e crescimento.',
        'descrmoderado': 'Valuation razoável, 10-15x (ex.: ABEV3). Justo para setores estáveis com EBIT consistente.',
        'descrbom': 'Valuation atrativo, 5-10x (ex.: ITUB4). Ideal para investidores de valor em 2025.',
        'descotimo': 'Valuation extremamente atrativo, <5x ou negativo devido a EV negativo com EBIT positivo (ex.: VALE3 em recuperação ou WEGR3 com alto caixa). Oportunidade em 2025, verificar alocação de caixa e sustentabilidade do EBIT.'
    },
    'EV/EBITDA': {
        'pessimo': [
            {'min': float('-inf'), 'max': 0, 'condicao': 'EBITDA negativo'},
            {'min': 15, 'max': float('inf'), 'condicao': 'Valuation elevado'}
        ],
        'ruim': {'min': 10, 'max': 15},
        'moderado': {'min': 7, 'max': 10},
        'bom': {'min': 4, 'max': 7},
        'otimo': {'min': float('-inf'), 'max': 4, 'condicao': 'EV negativo com EBITDA positivo ou baixo múltiplo'},
        'descricao': 'Relação entre valor da empresa e EBITDA. Valores muito baixos ou negativos (EV negativo com EBITDA positivo) sugerem subvalorização.',
        'agrupador': 'Valuation',
        'descrpessimo': 'Valuation elevado (>15x, ex.: startups tech) ou EBITDA negativo (ex.: OIBR3). Alto risco, evitar em 2025 salvo crescimento excepcional.',
        'descrruim': 'Valuation alto, 10-15x (ex.: MGLU3). Cautela, verificar crescimento do EBITDA.',
        'descrmoderado': 'Valuation razoável, 7-10x (ex.: ABEV3). Justo para setores estáveis.',
        'descrbom': 'Valuation atrativo, 4-7x (ex.: ITUB4). Ideal em 2025.',
        'descotimo': 'Valuation extremamente atrativo, <4x ou negativo devido a EV negativo com EBITDA positivo (ex.: VALE3 ou WEGR3). Oportunidade, verificar alocação de caixa.'
    },
    'P/ATIVO': {
        'pessimo': {'min': 2, 'max': float('inf')},
        'ruim': {'min': 1.5, 'max': 2},
        'moderado': {'min': 1, 'max': 1.5},
        'bom': {'min': 0.5, 'max': 1},
        'otimo': {'min': 0, 'max': 0.5},
        'descricao': 'Relação entre preço e ativos totais. Indica valuation.',
        'agrupador': 'Valuation',
        'descrpessimo': 'Valuation elevado, >2x (ex.: MGLU3). Evitar em 2025.',
        'descrruim': 'Valuation alto, 1,5-2x (ex.: startups). Cautela.',
        'descrmoderado': 'Valuation razoável, 1-1,5x (ex.: ABEV3). Justo.',
        'descrbom': 'Valuation atrativo, 0,5-1x (ex.: ITUB4). Ideal.',
        'descotimo': 'Valuation muito atrativo, <0,5x (ex.: VALE3). Oportunidade.'
    },
    'P/Ativo Circulante Líquido': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 2, 'max': float('inf')},
        'moderado': {'min': 1, 'max': 2},
        'bom': {'min': 0.5, 'max': 1},
        'otimo': {'min': 0, 'max': 0.5},
        'descricao': 'Relação entre preço e ativo circulante líquido. Indica valuation e liquidez.',
        'agrupador': 'Valuation',
        'descrpessimo': 'Ativo circulante líquido negativo ou valuation muito elevado (ex.: OIBR3). Evitar.',
        'descrruim': 'Valuation alto, >2x (ex.: MGLU3). Cautela.',
        'descrmoderado': 'Valuation razoável, 1-2x (ex.: ABEV3). Justo.',
        'descrbom': 'Valuation atrativo, 0,5-1x (ex.: ITUB4). Ideal.',
        'descotimo': 'Valuation muito atrativo, <0,5x (ex.: VALE3). Oportunidade.'
    },
    'P/Capital de Giro': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 3, 'max': float('inf')},
        'moderado': {'min': 1.5, 'max': 3},
        'bom': {'min': 0.5, 'max': 1.5},
        'otimo': {'min': 0, 'max': 0.5},
        'descricao': 'Relação entre preço e capital de giro. Indica valuation e eficiência.',
        'agrupador': 'Valuation',
        'descrpessimo': 'Capital de giro negativo ou valuation muito elevado (ex.: OIBR3). Evitar.',
        'descrruim': 'Valuation alto, >3x (ex.: MGLU3). Cautela.',
        'descrmoderado': 'Valuation razoável, 1,5-3x (ex.: ABEV3). Justo.',
        'descrbom': 'Valuation atrativo, 0,5-1,5x (ex.: ITUB4). Ideal.',
        'descotimo': 'Valuation muito atrativo, <0,5x (ex.: VALE3). Oportunidade.'
    },
    'P/EBIT': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 20, 'max': float('inf')},
        'moderado': {'min': 15, 'max': 20},
        'bom': {'min': 10, 'max': 15},
        'otimo': {'min': 0, 'max': 10},
        'descricao': 'Relação entre preço e EBIT. Indica valuation operacional.',
        'agrupador': 'Valuation',
        'descrpessimo': 'EBIT negativo ou valuation elevado, >20x (ex.: OIBR3). Evitar.',
        'descrruim': 'Valuation alto, 20x+ (ex.: MGLU3). Cautela.',
        'descrmoderado': 'Valuation razoável, 15-20x (ex.: ABEV3). Justo.',
        'descrbom': 'Valuation atrativo, 10-15x (ex.: ITUB4). Ideal.',
        'descotimo': 'Valuation muito atrativo, <10x (ex.: VALE3). Oportunidade.'
    },
    'P/EBITDA': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 10, 'max': float('inf')},
        'moderado': {'min': 7, 'max': 10},
        'bom': {'min': 4, 'max': 7},
        'otimo': {'min': 0, 'max': 4},
        'descricao': 'Relação entre preço e EBITDA. Indica valuation operacional.',
        'agrupador': 'Valuation',
        'descrpessimo': 'EBITDA negativo ou valuation elevado, >10x (ex.: OIBR3). Evitar.',
        'descrruim': 'Valuation alto, 10x+ (ex.: MGLU3). Cautela.',
        'descrmoderado': 'Valuation razoável, 7-10x (ex.: ABEV3). Justo.',
        'descrbom': 'Valuation atrativo, 4-7x (ex.: ITUB4). Ideal.',
        'descotimo': 'Valuation muito atrativo, <4x (ex.: VALE3). Oportunidade.'
    },
    'P/L': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 20, 'max': float('inf')},
        'moderado': {'min': 15, 'max': 20},
        'bom': {'min': 10, 'max': 15},
        'otimo': {'min': 0, 'max': 10},
        'descricao': 'Relação entre preço e lucro líquido. Indica valuation.',
        'agrupador': 'Valuation',
        'descrpessimo': 'Lucro negativo ou valuation elevado, >20x (ex.: OIBR3). Evitar.',
        'descrruim': 'Valuation alto, 20x+ (ex.: MGLU3). Cautela.',
        'descrmoderado': 'Valuation razoável, 15-20x (ex.: ABEV3). Justo.',
        'descrbom': 'Valuation atrativo, 10-15x (ex.: ITUB4). Ideal.',
        'descotimo': 'Valuation muito atrativo, <10x (ex.: VALE3). Oportunidade.'
    },
    'P/VPA': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 2, 'max': float('inf')},
        'moderado': {'min': 1.5, 'max': 2},
        'bom': {'min': 1, 'max': 1.5},
        'otimo': {'min': 0, 'max': 1},
        'descricao': 'Relação entre preço e valor patrimonial por ação. Indica valuation.',
        'agrupador': 'Valuation',
        'descrpessimo': 'VPA negativo ou valuation elevado, >2x (ex.: OIBR3). Evitar.',
        'descrruim': 'Valuation alto, 2x+ (ex.: MGLU3). Cautela.',
        'descrmoderado': 'Valuation razoável, 1,5-2x (ex.: ABEV3). Justo.',
        'descrbom': 'Valuation atrativo, 1-1,5x (ex.: ITUB4). Ideal.',
        'descotimo': 'Valuation muito atrativo, <1x (ex.: VALE3). Oportunidade.'
    },
    'PSR': {
        'pessimo': {'min': 3, 'max': float('inf')},
        'ruim': {'min': 2, 'max': 3},
        'moderado': {'min': 1, 'max': 2},
        'bom': {'min': 0.5, 'max': 1},
        'otimo': {'min': 0, 'max': 0.5},
        'descricao': 'Relação entre preço e receita. Indica valuation em relação às vendas.',
        'agrupador': 'Valuation',
        'descrpessimo': 'Valuation elevado, >3x (ex.: startups). Evitar.',
        'descrruim': 'Valuation alto, 2-3x (ex.: MGLU3). Cautela.',
        'descrmoderado': 'Valuation razoável, 1-2x (ex.: ABEV3). Justo.',
        'descrbom': 'Valuation atrativo, 0,5-1x (ex.: ITUB4). Ideal.',
        'descotimo': 'Valuation muito atrativo, <0,5x (ex.: VALE3). Oportunidade.'
    },
    'Giro do Ativo': {
        'pessimo': {'min': 0, 'max': 0.5},
        'ruim': {'min': 0.5, 'max': 1},
        'moderado': {'min': 1, 'max': 1.5},
        'bom': {'min': 1.5, 'max': 2},
        'otimo': {'min': 2, 'max': float('inf')},
        'descricao': 'Eficiência na geração de receita por ativo. Indica produtividade.',
        'agrupador': 'Eficiência',
        'descrpessimo': 'Baixa eficiência, <0,5x (ex.: OIBR3). Evitar.',
        'descrruim': 'Eficiência limitada, 0,5-1x (ex.: CSNA3). Cautela.',
        'descrmoderado': 'Eficiência razoável, 1-1,5x (ex.: ABEV3). Justo.',
        'descrbom': 'Alta eficiência, 1,5-2x (ex.: ITUB4). Ideal.',
        'descotimo': 'Eficiência excepcional, >2x (ex.: WEGR3). Atraente.'
    },
    'Liquidez Corrente': {
        'pessimo': {'min': 0, 'max': 1},
        'ruim': {'min': 1, 'max': 1.2},
        'moderado': {'min': 1.2, 'max': 1.5},
        'bom': {'min': 1.5, 'max': 2},
        'otimo': {'min': 2, 'max': float('inf')},
        'descricao': 'Capacidade de cobrir passivos de curto prazo com ativos circulantes.',
        'agrupador': 'Liquidez',
        'descrpessimo': 'Baixa liquidez, <1 (ex.: OIBR3). Evitar.',
        'descrruim': 'Liquidez limitada, 1-1,2 (ex.: CSNA3). Cautela.',
        'descrmoderado': 'Liquidez razoável, 1,2-1,5 (ex.: ABEV3). Justo.',
        'descrbom': 'Boa liquidez, 1,5-2 (ex.: ITUB4). Ideal.',
        'descotimo': 'Liquidez excepcional, >2 (ex.: WEGR3). Atraente.'
    },
    'LPA': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 0.5},
        'moderado': {'min': 0.5, 'max': 1},
        'bom': {'min': 1, 'max': 2},
        'otimo': {'min': 2, 'max': float('inf')},
        'descricao': 'Lucro por ação. Indica rentabilidade por ação.',
        'agrupador': 'Rentabilidade',
        'descrpessimo': 'Prejuízo por ação (ex.: OIBR3). Evitar.',
        'descrruim': 'Lucro baixo, 0-0,5 (ex.: CSNA3). Cautela.',
        'descrmoderado': 'Lucro razoável, 0,5-1 (ex.: ABEV3). Justo.',
        'descrbom': 'Lucro sólido, 1-2 (ex.: ITUB4). Ideal.',
        'descotimo': 'Lucro excepcional, >2 (ex.: WEGR3). Atraente.'
    },
    'Margem Bruta': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 10},
        'moderado': {'min': 10, 'max': 20},
        'bom': {'min': 20, 'max': 30},
        'otimo': {'min': 30, 'max': float('inf')},
        'descricao': 'Percentual de lucro bruto sobre receita. Indica eficiência operacional.',
        'agrupador': 'Rentabilidade',
        'descrpessimo': 'Margem negativa ou muito baixa, <10% (ex.: OIBR3). Evitar.',
        'descrruim': 'Margem limitada, 10-20% (ex.: CSNA3). Cautela.',
        'descrmoderado': 'Margem razoável, 20-30% (ex.: ABEV3). Justo.',
        'descrbom': 'Margem sólida, 30-50% (ex.: ITUB4). Ideal.',
        'descotimo': 'Margem excepcional, >50% (ex.: WEGR3). Atraente.'
    },
    'Margem EBIT': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 5},
        'moderado': {'min': 5, 'max': 10},
        'bom': {'min': 10, 'max': 15},
        'otimo': {'min': 15, 'max': float('inf')},
        'descricao': 'Percentual de lucro operacional sobre receita. Indica eficiência.',
        'agrupador': 'Rentabilidade',
        'descrpessimo': 'Margem negativa ou muito baixa, <5% (ex.: OIBR3). Evitar.',
        'descrruim': 'Margem limitada, 5-10% (ex.: CSNA3). Cautela.',
        'descrmoderado': 'Margem razoável, 10-15% (ex.: ABEV3). Justo.',
        'descrbom': 'Margem sólida, 15-25% (ex.: ITUB4). Ideal.',
        'descotimo': 'Margem excepcional, >25% (ex.: WEGR3). Atraente.'
    },
    'Margem EBITDA': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 10},
        'moderado': {'min': 10, 'max': 15},
        'bom': {'min': 15, 'max': 20},
        'otimo': {'min': 20, 'max': float('inf')},
        'descricao': 'Percentual de EBITDA sobre receita. Indica geração de caixa operacional.',
        'agrupador': 'Rentabilidade',
        'descrpessimo': 'Margem negativa ou muito baixa, <10% (ex.: OIBR3). Evitar.',
        'descrruim': 'Margem limitada, 10-15% (ex.: CSNA3). Cautela.',
        'descrmoderado': 'Margem razoável, 15-20% (ex.: ABEV3). Justo.',
        'descrbom': 'Margem sólida, 20-30% (ex.: ITUB4). Ideal.',
        'descotimo': 'Margem excepcional, >30% (ex.: WEGR3). Atraente.'
    },
    'Margem Líquida': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 5},
        'moderado': {'min': 5, 'max': 10},
        'bom': {'min': 10, 'max': 20},
        'otimo': {'min': 20, 'max': float('inf')},
        'descricao': 'Percentual de lucro líquido sobre receita. Indica rentabilidade final.',
        'agrupador': 'Rentabilidade',
        'descrpessimo': 'Prejuízo líquido, <0% (ex.: OIBR3). Evitar.',
        'descrruim': 'Margem baixa, 0-5% (ex.: CSNA3). Cautela.',
        'descrmoderado': 'Margem razoável, 5-10% (ex.: ABEV3). Justo.',
        'descrbom': 'Margem sólida, 10-20% (ex.: ITUB4). Ideal.',
        'descotimo': 'Margem excepcional, >20% (ex.: WEGR3). Atraente.'
    },
    'ROA': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 5},
        'moderado': {'min': 5, 'max': 10},
        'bom': {'min': 10, 'max': 15},
        'otimo': {'min': 15, 'max': float('inf')},
        'descricao': 'Retorno sobre ativos. Indica eficiência na utilização dos ativos.',
        'agrupador': 'Rentabilidade',
        'descrpessimo': 'Retorno negativo, <0% (ex.: OIBR3). Evitar.',
        'descrruim': 'Retorno baixo, 0-5% (ex.: CSNA3). Cautela.',
        'descrmoderado': 'Retorno razoável, 5-10% (ex.: ABEV3). Justo.',
        'descrbom': 'Retorno sólido, 10-15% (ex.: ITUB4). Ideal.',
        'descotimo': 'Retorno excepcional, >15% (ex.: WEGR3). Atraente.'
    },
    'ROE': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 10},
        'moderado': {'min': 10, 'max': 15},
        'bom': {'min': 15, 'max': 20},
        'otimo': {'min': 20, 'max': float('inf')},
        'descricao': 'Retorno sobre patrimônio líquido. Indica rentabilidade para acionistas.',
        'agrupador': 'Rentabilidade',
        'descrpessimo': 'Retorno negativo, <0% (ex.: OIBR3). Evitar.',
        'descrruim': 'Retorno baixo, 0-10% (ex.: CSNA3). Cautela.',
        'descrmoderado': 'Retorno razoável, 10-15% (ex.: ABEV3). Justo.',
        'descrbom': 'Retorno sólido, 15-20% (ex.: ITUB4). Ideal.',
        'descotimo': 'Retorno excepcional, >20% (ex.: WEGR3). Atraente.'
    },
    'CAGR Lucros 5 anos': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 5},
        'moderado': {'min': 5, 'max': 10},
        'bom': {'min': 10, 'max': 20},
        'otimo': {'min': 20, 'max': float('inf')},
        'descricao': 'Crescimento anual composto dos lucros em 5 anos. Indica tendência de crescimento.',
        'agrupador': 'Rentabilidade',
        'descrpessimo': 'Crescimento negativo, <0% (ex.: OIBR3). Evitar.',
        'descrruim': 'Crescimento baixo, 0-5% (ex.: CSNA3). Cautela.',
        'descrmoderado': 'Crescimento razoável, 5-10% (ex.: ABEV3). Justo.',
        'descrbom': 'Crescimento sólido, 10-20% (ex.: ITUB4). Ideal.',
        'descotimo': 'Crescimento excepcional, >20% (ex.: WEGR3). Atraente.'
    },
    'ROIC': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 5},
        'moderado': {'min': 5, 'max': 10},
        'bom': {'min': 10, 'max': 15},
        'otimo': {'min': 15, 'max': float('inf')},
        'descricao': 'Retorno sobre capital investido. Indica eficiência do capital.',
        'agrupador': 'Rentabilidade',
        'descrpessimo': 'Retorno negativo, <0% (ex.: OIBR3). Evitar.',
        'descrruim': 'Retorno baixo, 0-5% (ex.: CSNA3). Cautela.',
        'descrmoderado': 'Retorno razoável, 5-10% (ex.: ABEV3). Justo.',
        'descrbom': 'Retorno sólido, 10-15% (ex.: ITUB4). Ideal.',
        'descotimo': 'Retorno excepcional, >15% (ex.: WEGR3). Atraente.'
    },
    'VPA': {
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 1},
        'moderado': {'min': 1, 'max': 5},
        'bom': {'min': 5, 'max': 10},
        'otimo': {'min': 10, 'max': float('inf')},
        'descricao': 'Valor patrimonial por ação. Indica valor contábil por ação.',
        'agrupador': 'Rentabilidade',
        'descrpessimo': 'Valor patrimonial negativo (ex.: OIBR3). Evitar.',
        'descrruim': 'Valor patrimonial baixo, 0-1 (ex.: CSNA3). Cautela.',
        'descrmoderado': 'Valor patrimonial razoável, 1-5 (ex.: ABEV3). Justo.',
        'descrbom': 'Valor patrimonial sólido, 5-10 (ex.: ITUB4). Ideal.',
        'descotimo': 'Valor patrimonial excepcional, >10 (ex.: WEGR3). Atraente.'
    }
}
