indicadores = {
    'Dívida Líquida/EBIT': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': 4, 'max': float('inf')},
        'ruim': {'min': 3, 'max': 4},
        'moderado': {'min': 1.5, 'max': 3},
        'bom': {'min': 0, 'max': 1.5},
        'otimo': {'min': 0, 'max': 1.5},
        'descricao': 'Dívida líquida dividida pelo EBIT. Mede tempo para quitar dívida com lucro operacional.',
        'agrupador': 'Endividamento',
        'descrcritico': 'Dívida líquida negativa pode indicar EBIT negativo (prejuízo operacional grave) ou excesso de caixa líquido. EBIT negativo, comum em empresas em crise (ex.: OI, OIBR3), reflete ineficiência operacional e risco de insolvência. Excesso de caixa, como em empresas de tecnologia (ex.: Nubank), pode indicar ineficiência na alocação de capital, com caixa ocioso não reinvestido. Em 2025, com juros altos, EBIT negativo agrava a pressão financeira. Investidores devem analisar a causa (EBIT negativo vs. caixa elevado) e evitar empresas sem plano claro de recuperação ou alocação eficiente.',
        'descrpessimo': 'Endividamento crítico, leva mais de 4 anos de EBIT para quitar a dívida líquida, indicando alavancagem extrema. Comum em empresas em crise ou setores cíclicos (ex.: construção, MRVE3). Em 2025, com juros de 10-12%, aumenta a vulnerabilidade a choques econômicos. Investidores devem evitar, salvo reestruturação robusta com forte geração de caixa e redução de dívida planejada.',
        'descrruim': 'Endividamento elevado, leva 3-4 anos de EBIT para pagar a dívida, um nível alto para a maioria dos setores. Comum em setores intensivos em capital (ex.: infraestrutura, CMIG4). Investidores devem analisar cobertura de juros (EBIT/juros > 2) e estabilidade do EBIT para avaliar riscos em cenários de alta volatilidade ou aumento de juros.',
        'descrmoderado': 'Endividamento moderado, pagável em 1,5-3 anos de EBIT, aceitável em setores estáveis (ex.: utilities, EGIE3). Investidores devem verificar consistência do EBIT (variação < 15% em 5 anos) e fluxo de caixa livre (FCL > CAPEX) para garantir que a alavancagem não comprometa a operação.',
        'descrbom': 'Endividamento controlado, dívida quitável em menos de 1,5 anos de EBIT, indicando baixa alavancagem. Comum em empresas maduras com forte geração de caixa (ex.: Ambev, ABEV3). Sinal de estabilidade financeira, mas deve-se avaliar se a baixa dívida reflete subinvestimento ou falta de oportunidades de crescimento.',
        'descrotimo': 'Endividamento controlado, dívida quitável em menos de 1,5 anos de EBIT, indicando baixa alavancagem. Comum em empresas maduras com forte geração de caixa (ex.: Ambev, ABEV3). Sinal de estabilidade financeira, mas deve-se avaliar se a baixa dívida reflete subinvestimento ou falta de oportunidades de crescimento.'
    },
    'Dívida Líquida/EBITDA': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': 3.5, 'max': float('inf')},
        'ruim': {'min': 2.5, 'max': 3.5},
        'moderado': {'min': 1, 'max': 2.5},
        'bom': {'min': 0, 'max': 1},
        'otimo': {'min': 0, 'max': 1},
        'descricao': 'Dívida líquida dividida pelo EBITDA. Mede tempo para quitar dívida com caixa operacional.',
        'agrupador': 'Endividamento',
        'descrcritico': 'Dívida líquida negativa pode indicar EBITDA negativo (prejuízo operacional grave) ou excesso de caixa líquido. EBITDA negativo, comum em empresas em crise (ex.: OI, OIBR3), reflete ineficiência grave e risco de insolvência. Excesso de caixa pode indicar alocação ineficiente, com recursos ociosos (ex.: tecnologia com caixa elevado, Nubank). Em 2025, EBITDA negativo aumenta vulnerabilidade a juros altos. Investidores devem analisar a causa (EBITDA negativo vs. caixa elevado) e exigir plano de recuperação ou alocação eficiente do caixa.',
        'descrpessimo': 'Endividamento crítico, leva mais de 3,5 anos de EBITDA para quitar a dívida líquida, indicando alavancagem extrema. Comum em setores cíclicos (ex.: commodities, VALE3). Em 2025, com juros de 10-12%, aumenta o risco de default em recessões. Investidores devem evitar, salvo recuperação clara com forte geração de caixa e redução de dívida planejada.',
        'descrruim': 'Endividamento elevado, leva 2,5-3,5 anos de EBITDA para pagar a dívida. Comum em setores com alta alavancagem (ex.: energia, CMIG4). Investidores devem analisar cobertura de juros (EBITDA/juros > 2,5) e volatilidade do EBITDA para avaliar riscos macroeconômicos, como aumento de custos ou queda de demanda.',
        'descrmoderado': 'Endividamento moderado, pagável em 1-2,5 anos de EBITDA, aceitável em setores com investimentos moderados (ex.: varejo, LREN3). Investidores devem monitorar tendência do EBITDA (crescimento > 5% ao ano) e gestão de dívidas para garantir sustentabilidade financeira em cenários adversos.',
        'descrbom': 'Endividamento baixo, dívida quitável rapidamente, indicando forte capacidade de pagamento. Comum em empresas com margens altas (ex.: Weg, WEGE3). Em 2025, reflete saúde financeira, mas deve-se avaliar se a baixa dívida limita expansão ou reinvestimento em mercados competitivos.',
        'descrotimo': 'Endividamento baixo, dívida quitável rapidamente, indicando forte capacidade de pagamento. Comum em empresas com margens altas (ex.: Weg, WEGE3). Em 2025, reflete saúde financeira, mas deve-se avaliar se a baixa dívida limita expansão ou reinvestimento em mercados competitivos.'
    },
    'Dívida Líquida/Patrimônio Líquido': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': 1, 'max': float('inf')},
        'ruim': {'min': 0.7, 'max': 1},
        'moderado': {'min': 0.3, 'max': 0.7},
        'bom': {'min': 0, 'max': 0.3},
        'otimo': {'min': 0, 'max': 0.3},
        'descricao': 'Dívida líquida em relação ao patrimônio líquido. Mede alavancagem financeira.',
        'agrupador': 'Endividamento',
        'descrcritico': 'Dívida líquida negativa pode indicar patrimônio líquido negativo (risco de insolvência) ou excesso de caixa líquido. Patrimônio negativo é comum em empresas em crise (ex.: OI, OIBR3), refletindo alavancagem insustentável. Excesso de caixa (ex.: Nubank) pode indicar ineficiência na alocação de capital. Em 2025, com juros de 10-12%, patrimônio negativo é alarmante. Investidores devem evitar, salvo reestruturação robusta ou plano claro de utilização do caixa.',
        'descrpessimo': 'Alavancagem extrema, com dívida líquida superando o patrimônio líquido, indicando alto risco financeiro. Comum em empresas com dificuldades financeiras (ex.: OI, OIBR3) ou setores cíclicos (ex.: construção, MRVE3). Em 2025, com juros altos, aumenta a vulnerabilidade. Investidores devem evitar, salvo sinais claros de recuperação e redução de dívida.',
        'descrruim': 'Endividamento elevado, com dívida líquida entre 70-100% do patrimônio líquido, indicando risco significativo. Comum em setores intensivos em capital (ex.: mineração, CSNA3). Investidores devem analisar capacidade de geração de caixa (EBITDA/juros > 2) e tendências de endividamento para avaliar sustentabilidade.',
        'descrmoderado': 'Endividamento moderado, aceitável em setores com fluxos estáveis (ex.: utilities, CPFE3). Dívida líquida representa 30-70% do patrimônio líquido, sugerindo alavancagem controlada. Investidores devem verificar consistência do lucro operacional e fluxo de caixa livre para garantir segurança financeira em cenários adversos.',
        'descrbom': 'Endividamento baixo, com dívida líquida inferior a 30% do patrimônio líquido, indicando saúde financeira. Comum em empresas maduras com forte geração de caixa (ex.: Engie, CPFE3). Em 2025, reflete estabilidade, mas deve-se avaliar se a baixa alavancagem limita crescimento.',
        'descrotimo': 'Endividamento baixo, com dívida líquida inferior a 30% do patrimônio líquido, indicando saúde financeira. Comum em empresas maduras com forte geração de caixa (ex.: Engie, CPFE3). Em 2025, reflete estabilidade, mas deve-se avaliar se a baixa alavancagem limita crescimento.'
    },
    'Dividend Yield (DY)': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': 0, 'max': 0},
        'ruim': {'min': 0.1, 'max': 2},
        'moderado': {'min': 2, 'max': 4},
        'bom': {'min': 4, 'max': 6},
        'otimo': {'min': 6, 'max': float('inf')},
        'descricao': 'Dividendos pagos por ação divididos pelo preço da ação. Mede retorno via dividendos.',
        'agrupador': 'Dividendos',
        'descrcritico': 'Não aplicável. Empresas com dividend yield negativo não existem, mas ausência de dividendos (0%) é tratada como péssimo para investidores focados em renda. Comum em empresas em crise (ex.: OI, OIBR3) ou que reinvestem todo o lucro (ex.: Nubank). Em 2025, com juros de 10-12%, ausência de dividendos é desvantajosa para estratégias de renda.',
        'descrpessimo': 'Ausência de dividendos, indicando que a empresa não distribui lucros aos acionistas. Comum em empresas em crescimento (ex.: Nubank) ou com dificuldades financeiras (ex.: OI, OIBR3). Para investidores de renda, é um sinal de alerta. Em 2025, com juros altos, prefira empresas com payout sustentável.',
        'descrruim': 'Dividend yield baixo, entre 0,1-2%, insuficiente para estratégias de renda em 2025, com juros de 10-12%. Comum em empresas com lucros limitados (ex.: Magazine Luiza, MGLU3). Investidores devem avaliar payout ratio (< 70%) e sustentabilidade dos dividendos em cenários adversos.',
        'descrmoderado': 'Dividend yield razoável, entre 2-4%, aceitável para setores com margens moderadas (ex.: consumo, ABEV3). Em 2025, com juros altos, oferece retorno competitivo, mas requer análise da sustentabilidade do payout (lucro líquido > dividendos) e estabilidade do fluxo de caixa.',
        'descrbom': 'Dividend yield sólido, entre 4-6%, atrativo para investidores de renda. Comum em setores maduros com forte geração de caixa (ex.: bancos, ITUB4). Em 2025, reflete equilíbrio entre retorno e segurança. Analise consistência dos lucros e payout ratio (< 70%) para confirmar sustentabilidade.',
        'descrotimo': 'Dividend yield elevado, acima de 6%, excepcional para estratégias de renda. Comum em setores com fluxos previsíveis (ex.: mineração, VALE3). Em 2025, com juros de 10-12%, é altamente atrativo, mas exige análise rigorosa do payout ratio e fluxo de caixa livre para evitar armadilhas de dividendos insustentáveis.'
    },
    'EV/EBIT': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': 15, 'max': float('inf')},
        'ruim': {'min': 12, 'max': 15},
        'moderado': {'min': 8, 'max': 12},
        'bom': {'min': 4, 'max': 8},
        'otimo': {'min': 0, 'max': 4},
        'descricao': 'Valor da empresa dividido pelo EBIT. Mede valuation em relação ao lucro operacional.',
        'agrupador': 'Valuation',
        'descrcritico': 'EV/EBIT negativo reflete EBIT negativo, indicando prejuízo operacional grave. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, com juros de 10-12%, é um sinal de alto risco. Investidores devem evitar, salvo recuperação clara com turnaround operacional.',
        'descrpessimo': 'Valuation elevado, com EV/EBIT acima de 15x, indicando que a empresa está sobrevalorizada em relação ao lucro operacional. Comum em empresas de crescimento (ex.: Nubank) ou setores especulativos. Em 2025, reflete otimismo excessivo. Investidores devem evitar, salvo forte crescimento do EBIT (> 15% ao ano).',
        'descrruim': 'Valuation caro, com EV/EBIT entre 12-15x, sugerindo preço elevado em relação ao lucro operacional. Comum em setores com margens moderadas (ex.: saúde, RDOR3). Investidores devem analisar crescimento do EBIT e comparar com peers para avaliar se o preço é justificado.',
        'descrmoderado': 'Valuation justo, com EV/EBIT entre 8-12x, aceitável para setores com crescimento moderado (ex.: siderurgia, CSNA3). Em 2025, reflete equilíbrio entre preço e lucro operacional. Investidores devem verificar sustentabilidade do EBIT e tendências setoriais (ex.: demanda global).',
        'descrbom': 'Valuation atrativo, com EV/EBIT entre 4-8x, indicando empresa subvalorizada em relação ao lucro operacional. Comum em setores cíclicos em recuperação (ex.: mineração, VALE3). Em 2025, é uma oportunidade, mas exige análise do ciclo econômico e consistência do EBIT.',
        'descrotimo': 'Valuation muito atrativo, com EV/EBIT entre 0-4x, indicando empresa extremamente subvalorizada. Comum em setores com lucros elevados (ex.: siderurgia, GGBR4). Em 2025, é uma oportunidade rara, mas requer confirmação de sustentabilidade do EBIT e ausência de riscos ocultos (ex.: litígios).'
    },
    'EV/EBITDA': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': 12, 'max': float('inf')},
        'ruim': {'min': 10, 'max': 12},
        'moderado': {'min': 6, 'max': 10},
        'bom': {'min': 3, 'max': 6},
        'otimo': {'min': 0, 'max': 3},
        'descricao': 'Valor da empresa dividido pelo EBITDA. Mede valuation em relação ao caixa operacional.',
        'agrupador': 'Valuation',
        'descrcritico': 'EV/EBITDA negativo reflete EBITDA negativo, indicando incapacidade de gerar caixa operacional. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, com juros altos, é um sinal de risco extremo. Investidores devem evitar, salvo recuperação robusta.',
        'descrpessimo': 'Valuation elevado, com EV/EBITDA acima de 12x, indicando que a empresa está sobrevalorizada em relação ao caixa operacional. Comum em empresas de tecnologia (ex.: Nubank) ou setores com otimismo exagerado. Em 2025, reflete risco de correção. Investidores devem exigir forte crescimento do EBITDA (> 15% ao ano).',
        'descrruim': 'Valuation caro, com EV/EBITDA entre 10-12x, sugerindo preço elevado em relação ao caixa operacional. Comum em setores com margens moderadas (ex.: saúde, RDOR3). Investidores devem comparar com peers e avaliar crescimento do EBITDA para justificar o preço.',
        'descrmoderado': 'Valuation justo, com EV/EBITDA entre 6-10x, aceitável para setores com crescimento moderado (ex.: varejo, LREN3). Em 2025, reflete equilíbrio entre preço e caixa operacional. Investidores devem verificar sustentabilidade do EBITDA e tendências setoriais (ex.: consumo).',
        'descrbom': 'Valuation atrativo, com EV/EBITDA entre 3-6x, indicando empresa subvalorizada em relação ao caixa operacional. Comum em setores cíclicos em recuperação (ex.: mineração, VALE3). Em 2025, é uma oportunidade, mas exige análise do ciclo econômico e estabilidade do EBITDA.',
        'descrotimo': 'Valuation muito atrativo, com EV/EBITDA entre 0-3x, indicando empresa extremamente subvalorizada. Comum em setores com margens altas (ex.: siderurgia, GGBR4). Em 2025, é uma oportunidade rara, mas requer confirmação de sustentabilidade do EBITDA e ausência de riscos ocultos.'
    },
    'Giro do Ativo': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': 0, 'max': 0.2},
        'ruim': {'min': 0.2, 'max': 0.4},
        'moderado': {'min': 0.4, 'max': 0.8},
        'bom': {'min': 0.8, 'max': 1.2},
        'otimo': {'min': 1.2, 'max': float('inf')},
        'descricao': 'Receita dividida pelos ativos totais. Mede eficiência na utilização de ativos.',
        'agrupador': 'Eficiência',
        'descrcritico': 'Não aplicável. Giro do ativo negativo implica receita negativa, extremamente raro (ex.: empresas em crise, OIBR3). Reflete ineficiência total na utilização de ativos. Em 2025, é um sinal de falência iminente. Investidores devem evitar, salvo reestruturação operacional robusta.',
        'descrpessimo': 'Eficiência extremamente baixa, com giro do ativo abaixo de 0,2, indicando subutilização grave dos ativos. Comum em setores intensivos em capital com baixa demanda (ex.: energia, CMIG4). Em 2025, reflete ineficiência operacional. Investidores devem evitar, salvo sinais de recuperação operacional.',
        'descrruim': 'Eficiência baixa, com giro do ativo entre 0,2-0,4, indicando utilização limitada dos ativos. Comum em setores cíclicos com margens apertadas (ex.: siderurgia, CSNA3). Investidores devem analisar capacidade de aumentar receita ou reduzir ativos ociosos para melhorar eficiência.',
        'descrmoderado': 'Eficiência moderada, com giro do ativo entre 0,4-0,8, aceitável para setores com investimentos pesados (ex.: siderurgia, GGBR4). Em 2025, reflete operação razoável, mas com espaço para melhorias. Investidores devem verificar estratégias de automação e aumento de receita.',
        'descrbom': 'Eficiência sólida, com giro do ativo entre 0,8-1,2, indicando boa utilização dos ativos. Comum em setores com operações enxutas (ex.: varejo, MGLU3). Em 2025, reflete competitividade. Investidores devem confirmar sustentabilidade da receita e ausência de ativos ociosos.',
        'descrotimo': 'Eficiência excepcional, com giro do ativo acima de 1,2, indicando alta produtividade dos ativos. Comum em setores com alta rotatividade (ex.: varejo, LREN3). Em 2025, reflete liderança operacional. Investidores devem analisar barreiras de entrada e sustentabilidade da receita.'
    },
    'Liquidez Corrente': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': 0, 'max': 0.8},
        'ruim': {'min': 0.8, 'max': 1.2},
        'moderado': {'min': 1.2, 'max': 1.8},
        'bom': {'min': 1.8, 'max': 2.5},
        'otimo': {'min': 2.5, 'max': float('inf')},
        'descricao': 'Ativo circulante dividido pelo passivo circulante. Mede capacidade de pagar obrigações de curto prazo.',
        'agrupador': 'Liquidez',
        'descrcritico': 'Não aplicável. Liquidez corrente negativa implica passivo circulante maior que ativo circulante, indicando risco de insolvência imediata (ex.: OI, OIBR3). Em 2025, com juros altos, é um sinal de falência iminente. Investidores devem evitar, salvo reestruturação financeira robusta.',
        'descrpessimo': 'Liquidez extremamente baixa, abaixo de 0,8, indicando incapacidade de cobrir obrigações de curto prazo. Comum em empresas em crise (ex.: OI, OIBR3). Em 2025, reflete alto risco de default. Investidores devem evitar, salvo recuperação clara com aumento de capital ou renegociação de dívidas.',
        'descrruim': 'Liquidez frágil, entre 0,8-1,2, indicando dificuldade em cobrir obrigações de curto prazo. Comum em setores com margens apertadas (ex.: varejo, CRFB3). Investidores devem analisar fluxo de caixa operacional e acesso a crédito para avaliar riscos de liquidez.',
        'descrmoderado': 'Liquidez razoável, entre 1,2-1,8, aceitável para setores com fluxos moderados (ex.: siderurgia, CSNA3). Em 2025, reflete capacidade de cumprir obrigações, mas com margem limitada. Investidores devem verificar consistência do fluxo de caixa e gestão de estoques.',
        'descrbom': 'Liquidez sólida, entre 1,8-2,5, indicando boa capacidade de pagar obrigações de curto prazo. Comum em empresas com operações estáveis (ex.: consumo, ABEV3). Em 2025, reflete segurança financeira. Investidores devem confirmar sustentabilidade do fluxo de caixa.',
        'descrotimo': 'Liquidez excepcional, acima de 2,5, indicando forte capacidade de cobrir obrigações de curto prazo. Comum em setores com alta geração de caixa (ex.: varejo, LREN3). Em 2025, reflete robustez financeira, mas deve-se avaliar se excesso de liquidez indica subinvestimento.'
    },
    'LPA (Lucro por Ação)': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 0.1},
        'moderado': {'min': 0.1, 'max': 0.5},
        'bom': {'min': 0.5, 'max': 1},
        'otimo': {'min': 1, 'max': float('inf')},
        'descricao': 'Lucro líquido dividido pelo número de ações. Mede lucratividade por ação.',
        'agrupador': 'Rentabilidade',
        'descrcritico': 'Lucro por ação negativo, indicando prejuízo líquido. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, reflete alto risco financeiro. Investidores devem evitar, salvo plano de recuperação robusto com geração de lucro projetada.',
        'descrpessimo': 'Lucro por ação negativo, indicando prejuízo líquido. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, reflete alto risco financeiro. Investidores devem evitar, salvo plano de recuperação robusto com geração de lucro projetada.',
        'descrruim': 'Lucro por ação baixo, entre 0-0,1, indicando lucratividade limitada. Comum em empresas com margens apertadas (ex.: Magazine Luiza, MGLU3). Em 2025, reflete desafios para crescimento. Investidores devem analisar tendências de lucro e estratégias de expansão.',
        'descrmoderado': 'Lucro por ação moderado, entre 0,1-0,5, aceitável para setores com crescimento moderado (ex.: varejo, CRFB3). Em 2025, reflete operação razoável, mas com espaço para melhorias. Investidores devem verificar consistência do lucro e perspectivas de crescimento.',
        'descrbom': 'Lucro por ação sólido, entre 0,5-1, indicando boa lucratividade. Comum em setores maduros com forte geração de caixa (ex.: bancos, ITUB4). Em 2025, reflete estabilidade financeira. Investidores devem confirmar sustentabilidade do lucro e payout ratio.',
        'descrotimo': 'Lucro por ação excepcional, acima de 1, indicando alta lucratividade. Comum em setores com margens elevadas (ex.: tecnologia, WEGE3). Em 2025, reflete liderança financeira. Investidores devem analisar sustentabilidade do lucro e proteção contra concorrência.'
    },
    'Margem Bruta': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': 0, 'max': 15},
        'ruim': {'min': 15, 'max': 30},
        'moderado': {'min': 30, 'max': 50},
        'bom': {'min': 50, 'max': 70},
        'otimo': {'min': 70, 'max': float('inf')},
        'descricao': 'Lucro bruto dividido pela receita. Mede eficiência na cobertura de custos diretos.',
        'agrupador': 'Rentabilidade',
        'descrcritico': 'Não aplicável. Margem bruta negativa implica custos diretos superando a receita, extremamente raro (ex.: OI, OIBR3). Reflete ineficiência grave na operação. Em 2025, é um sinal de falência iminente. Investidores devem evitar, salvo reestruturação operacional robusta.',
        'descrpessimo': 'Margem bruta extremamente baixa, abaixo de 15%, indicando ineficiência na cobertura de custos diretos. Comum em setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, reflete desafios para rentabilidade. Investidores devem analisar poder de precificação e corte de custos.',
        'descrruim': 'Margem bruta baixa, entre 15-30%, indicando eficiência limitada na cobertura de custos diretos. Comum em setores com margens apertadas (ex.: varejo, CRFB3). Investidores devem verificar estratégias de redução de custos e diferenciação para melhorar margens.',
        'descrmoderado': 'Margem bruta razoável, entre 30-50%, aceitável para setores com operações moderadas (ex.: consumo, ABEV3). Em 2025, reflete capacidade de cobrir custos diretos, mas com espaço para melhorias. Investidores devem comparar com peers e analisar poder de precificação.',
        'descrbom': 'Margem bruta sólida, entre 50-70%, indicando forte eficiência na cobertura de custos diretos. Comum em setores com barreiras de entrada (ex.: indústria, WEGE3). Em 2025, reflete competitividade. Investidores devem confirmar sustentabilidade da margem e proteção contra concorrência.',
        'descrotimo': 'Margem bruta excepcional, acima de 70%, indicando liderança na eficiência operacional. Comum em setores de alta margem (ex.: tecnologia, TOTS3). Em 2025, reflete vantagem competitiva. Investidores devem analisar sustentabilidade da margem e tendências setoriais.'
    },
    'Margem EBIT': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 5},
        'moderado': {'min': 5, 'max': 15},
        'bom': {'min': 15, 'max': 25},
        'otimo': {'min': 25, 'max': float('inf')},
        'descricao': 'EBIT dividido pela receita. Mede rentabilidade operacional.',
        'agrupador': 'Rentabilidade',
        'descrcritico': 'Margem EBIT negativa, indicando prejuízo operacional antes de juros e impostos. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, com juros de 10-12%, reflete alto risco. Investidores devem evitar, salvo plano de recuperação robusto.',
        'descrpessimo': 'Margem EBIT negativa, indicando prejuízo operacional antes de juros e impostos. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, com juros de 10-12%, reflete alto risco. Investidores devem evitar, salvo plano de recuperação robusto.',
        'descrruim': 'Margem EBIT baixa, entre 0-5%, indicando rentabilidade operacional limitada. Comum em setores com margens apertadas (ex.: varejo, MGLU3). Investidores devem analisar redução de custos operacionais e poder de precificação para avaliar potencial de melhoria.',
        'descrmoderado': 'Margem EBIT moderada, entre 5-15%, aceitável para setores com operações moderadas (ex.: siderurgia, CSNA3). Em 2025, reflete operação razoável, mas com espaço para melhorias. Investidores devem verificar consistência do EBIT e tendências setoriais.',
        'descrbom': 'Margem EBIT sólida, entre 15-25%, indicando boa rentabilidade operacional. Comum em setores com barreiras de entrada (ex.: utilities, CPFE3). Em 2025, reflete competitividade. Investidores devem confirmar sustentabilidade do EBIT e fluxo de caixa livre.',
        'descrotimo': 'Margem EBIT excepcional, acima de 25%, indicando liderança na rentabilidade operacional. Comum em setores de alta margem (ex.: tecnologia, TOTS3). Em 2025, reflete vantagem competitiva. Investidores devem analisar sustentabilidade e proteção contra concorrência.'
    },
    'Margem EBITDA': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 10},
        'moderado': {'min': 10, 'max': 20},
        'bom': {'min': 20, 'max': 30},
        'otimo': {'min': 30, 'max': float('inf')},
        'descricao': 'EBITDA dividido pela receita. Mede geração de caixa operacional.',
        'agrupador': 'Rentabilidade',
        'descrcritico': 'Prejuízo operacional, com incapacidade de gerar caixa operacional. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, com juros de 10-12%, reflete alto risco de insolvência. Analise fluxo de caixa operacional (FCO < 0 é alarmante) e composição dos custos. Evite empresas com EBITDA negativo recorrente sem plano de recuperação robusto.',
        'descrpessimo': 'Prejuízo operacional, com incapacidade de gerar caixa operacional. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, com juros de 10-12%, reflete alto risco de insolvência. Analise fluxo de caixa operacional (FCO < 0 é alarmante) e composição dos custos. Evite empresas com EBITDA negativo recorrente sem plano de recuperação robusto.',
        'descrruim': 'Baixa geração de caixa, eficiência limitada. Comum em setores intensivos em capital (ex.: infraestrutura, CMIG4). Em 2025, reflete desafios para melhorar eficiência. Investidores devem analisar automação, corte de custos e poder de precificação. Riscos incluem concorrência agressiva e aumento de insumos. Compare com peers (ex.: varejo ~15%) e analise ROIC (> 5%).',
        'descrmoderado': 'Geração de caixa moderada, aceitável em setores com margens moderadas (ex.: varejo, LREN3). Em 2025, reflete capacidade de cobrir custos operacionais. Investidores devem comparar com peers (ex.: varejo ~15%) e verificar sustentabilidade do EBITDA (variação < 15% em 5 anos). Oportunidades em empresas com melhoria operacional.',
        'descrbom': 'Boa geração de caixa, eficiência sólida. Comum em setores com barreiras de entrada (ex.: utilities, CPFE3). In 2025, reflete capacidade de suportar custos elevados. Investidores devem verificar consistência do EBITDA e poder de precificação. Oportunidades em expansão ou inovação. Analise fluxo de caixa livre (FCL > CAPEX).',
        'descrotimo': 'Alta geração de caixa, desempenho excepcional. Comum em setores de alta margem (ex.: tecnologia, TOTS3). Em 2025, reflete liderança e eficiência. Investidores devem confirmar sustentabilidade e proteção contra concorrência. Analise ROIC (> 20%) e tendências setoriais (ex.: digitalização).'
    },
    'Margem Líquida': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 5},
        'moderado': {'min': 5, 'max': 10},
        'bom': {'min': 10, 'max': 20},
        'otimo': {'min': 20, 'max': float('inf')},
        'descricao': 'Lucro líquido dividido pela receita. Mede rentabilidade final.',
        'agrupador': 'Rentabilidade',
        'descrcritico': 'Margem líquida negativa, indicando prejuízo líquido após todas as despesas. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, reflete alto risco financeiro. Investidores devem evitar, salvo plano de recuperação robusto.',
        'descrpessimo': 'Margem líquida negativa, indicando prejuízo líquido após todas as despesas. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, reflete alto risco financeiro. Investidores devem evitar, salvo plano de recuperação robusto.',
        'descrruim': 'Margem líquida baixa, entre 0-5%, indicando rentabilidade final limitada. Comum em setores com margens apertadas (ex.: varejo, MGLU3). Investidores devem analisar redução de custos e estratégias de crescimento para avaliar potencial de melhoria.',
        'descrmoderado': 'Margem líquida moderada, entre 5-10%, aceitável para setores com operações moderadas (ex.: siderurgia, CSNA3). Em 2025, reflete operação razoável, mas com espaço para melhorias. Investidores devem verificar consistência do lucro líquido e tendências setoriais.',
        'descrbom': 'Margem líquida sólida, entre 10-20%, indicando boa rentabilidade final. Comum em setores maduros com forte geração de caixa (ex.: bancos, ITUB4). Em 2025, reflete estabilidade financeira. Investidores devem confirmar sustentabilidade do lucro e payout ratio.',
        'descrotimo': 'Margem líquida excepcional, acima de 20%, indicando liderança na rentabilidade final. Comum em setores de alta margem (ex.: tecnologia, TOTS3). Em 2025, reflete vantagem competitiva. Investidores devem analisar sustentabilidade e proteção contra concorrência.'
    },
    'P/Ativo Circulante Líquido': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 1},
        'moderado': {'min': 1, 'max': 2},
        'bom': {'min': 2, 'max': 3},
        'otimo': {'min': 3, 'max': float('inf')},
        'descricao': 'Preço dividido pelo ativo circulante líquido. Mede liquidez de curto prazo.',
        'agrupador': 'Liquidez',
        'descrcritico': 'P/Ativo circulante líquido negativo, indicando passivo circulante maior que ativo circulante, um sinal de insolvência iminente. Comum em empresas em crise (ex.: OI, OIBR3). Em 2025, reflete alto risco financeiro. Investidores devem evitar, salvo reestruturação robusta.',
        'descrpessimo': 'P/Ativo circulante líquido negativo, indicando passivo circulante maior que ativo circulante, um sinal de insolvência iminente. Comum em empresas em crise (ex.: OI, OIBR3). Em 2025, reflete alto risco financeiro. Investidores devem evitar, salvo reestruturação robusta.',
        'descrruim': 'P/Ativo circulante líquido baixo, entre 0-1, indicando liquidez frágil. Comum em setores com margens apertadas (ex.: varejo, CRFB3). Investidores devem analisar fluxo de caixa operacional e acesso a crédito para avaliar riscos de liquidez em curto prazo.',
        'descrmoderado': 'P/Ativo circulante líquido razoável, entre 1-2, aceitável para setores com fluxos moderados (ex.: siderurgia, CSNA3). Em 2025, reflete capacidade de cumprir obrigações, mas com margem limitada. Investidores devem verificar gestão de estoques e fluxo de caixa.',
        'descrbom': 'P/Ativo circulante líquido sólido, entre 2-3, indicando boa liquidez de curto prazo. Comum em empresas com operações estáveis (ex.: consumo, ABEV3). Em 2025, reflete segurança financeira. Investidores devem confirmar sustentabilidade do fluxo de caixa.',
        'descrotimo': 'P/Ativo circulante líquido excepcional, acima de 3, indicando forte liquidez de curto prazo. Comum em setores com alta geração de caixa (ex.: tecnologia, TOTS3). Em 2025, reflete robustez financeira, mas deve-se avaliar se excesso de liquidez indica subinvestimento.'
    },
    'P/Capital de Giro': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 2},
        'moderado': {'min': 2, 'max': 4},
        'bom': {'min': 4, 'max': 6},
        'otimo': {'min': 6, 'max': float('inf')},
        'descricao': 'Preço dividido pelo capital de giro. Mede capacidade de financiar operações.',
        'agrupador': 'Liquidez',
        'descrcritico': 'P/Capital de giro negativo, indicando capital de giro negativo, um sinal de insolvência iminente. Comum em empresas em crise (ex.: OI, OIBR3). Em 2025, reflete alto risco financeiro. Investidores devem evitar, salvo reestruturação robusta.',
        'descrpessimo': 'P/Capital de giro negativo, indicando capital de giro negativo, um sinal de insolvência iminente. Comum em empresas em crise (ex.: OI, OIBR3). Em 2025, reflete alto risco financeiro. Investidores devem evitar, salvo reestruturação robusta.',
        'descrruim': 'P/Capital de giro baixo, entre 0-2, indicando capacidade limitada de financiar operações. Comum em setores com margens apertadas (ex.: varejo, MGLU3). Investidores devem analisar fluxo de caixa operacional e gestão de capital de giro para avaliar riscos.',
        'descrmoderado': 'P/Capital de giro razoável, entre 2-4, aceitável para setores com fluxos moderados (ex.: siderurgia, CSNA3). Em 2025, reflete capacidade de financiar operações, mas com margem limitada. Investidores devem verificar eficiência na gestão de estoques e recebíveis.',
        'descrbom': 'P/Capital de giro sólido, entre 4-6, indicando boa capacidade de financiar operações. Comum em empresas com operações estáveis (ex.: utilities, CPFE3). Em 2025, reflete segurança financeira. Investidores devem confirmar sustentabilidade do fluxo de caixa.',
        'descrotimo': 'P/Capital de giro excepcional, acima de 6, indicando forte capacidade de financiar operações. Comum em setores com alta geração de caixa (ex.: tecnologia, TOTS3). Em 2025, reflete robustez financeira, mas deve-se avaliar se excesso de liquidez indica subinvestimento.'
    },
    'P/EBIT': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': 20, 'max': float('inf')},
        'ruim': {'min': 15, 'max': 20},
        'moderado': {'min': 10, 'max': 15},
        'bom': {'min': 5, 'max': 10},
        'otimo': {'min': 0, 'max': 5},
        'descricao': 'Preço dividido pelo EBIT. Mede valuation em relação ao lucro operacional.',
        'agrupador': 'Valuation',
        'descrcritico': 'P/EBIT negativo reflete EBIT negativo, indicando prejuízo operacional grave. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, com juros de 10-12%, é um sinal de alto risco. Investidores devem evitar, salvo recuperação clara.',
        'descrpessimo': 'Valuation elevado, com P/EBIT acima de 20x, indicando que a ação está sobrevalorizada em relação ao lucro operacional. Comum em empresas de crescimento (ex.: Nubank) ou setores especulativos. Em 2025, reflete otimismo excessivo. Investidores devem exigir forte crescimento do EBIT (> 15% ao ano).',
        'descrruim': 'Valuation caro, com P/EBIT entre 15-20x, sugerindo preço elevado em relação ao lucro operacional. Comum em setores com margens moderadas (ex.: saúde, RDOR3). Investidores devem analisar crescimento do EBIT e comparar com peers para avaliar se o preço é justificado.',
        'descrmoderado': 'Valuation justo, com P/EBIT entre 10-15x, aceitável para setores com crescimento moderado (ex.: siderurgia, CSNA3). Em 2025, reflete equilíbrio entre preço e lucro operacional. Investidores devem verificar sustentabilidade do EBIT e tendências setoriais.',
        'descrbom': 'Valuation atrativo, com P/EBIT entre 5-10x, indicando ação subvalorizada em relação ao lucro operacional. Comum em setores cíclicos em recuperação (ex.: mineração, VALE3). Em 2025, é uma oportunidade, mas exige análise do ciclo econômico e consistência do EBIT.',
        'descrotimo': 'Valuation muito atrativo, com P/EBIT entre 0-5x, indicando ação extremamente subvalorizada. Comum em setores com lucros elevados (ex.: siderurgia, GGBR4). Em 2025, é uma oportunidade rara, mas requer confirmação de sustentabilidade do EBIT e ausência de riscos ocultos.'
    },
    'P/EBITDA': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': 15, 'max': float('inf')},
        'ruim': {'min': 10, 'max': 15},
        'moderado': {'min': 6, 'max': 10},
        'bom': {'min': 3, 'max': 6},
        'otimo': {'min': 0, 'max': 3},
        'descricao': 'Preço dividido pelo EBITDA. Mede valuation em relação ao caixa operacional.',
        'agrupador': 'Valuation',
        'descrcritico': 'P/EBITDA negativo reflete EBITDA negativo, indicando incapacidade de gerar caixa operacional. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, com juros altos, é um sinal de risco extremo. Investidores devem evitar, salvo recuperação robusta.',
        'descrpessimo': 'Valuation elevado, com P/EBITDA acima de 15x, indicando que a ação está sobrevalorizada em relação ao caixa operacional. Comum em empresas de tecnologia (ex.: Nubank) ou setores com otimismo exagerado. Em 2025, reflete risco de correção. Investidores devem exigir forte crescimento do EBITDA (> 15% ao ano).',
        'descrruim': 'Valuation caro, com P/EBITDA entre 10-15x, sugerindo preço elevado em relação ao caixa operacional. Comum em setores com margens moderadas (ex.: saúde, RDOR3). Investidores devem comparar com peers e avaliar crescimento do EBITDA para justificar o preço.',
        'descrmoderado': 'Valuation justo, com P/EBITDA entre 6-10x, aceitável para setores com crescimento moderado (ex.: varejo, LREN3). Em 2025, reflete equilíbrio entre preço e caixa operacional. Investidores devem verificar sustentabilidade do EBITDA e tendências setoriais.',
        'descrbom': 'Valuation atrativo, com P/EBITDA entre 3-6x, indicando ação subvalorizada em relação ao caixa operacional. Comum em setores cíclicos em recuperação (ex.: mineração, VALE3). Em 2025, é uma oportunidade, mas exige análise do ciclo econômico e estabilidade do EBITDA.',
        'descrotimo': 'Valuation muito atrativo, com P/EBITDA entre 0-3x, indicando ação extremamente subvalorizada. Comum em setores com margens altas (ex.: siderurgia, GGBR4). Em 2025, é uma oportunidade rara, mas requer confirmação de sustentabilidade do EBITDA e ausência de riscos ocultos.'
    },
    'Preço sobre Lucro (P/L)': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': 20, 'max': float('inf')},
        'ruim': {'min': 15, 'max': 20},
        'moderado': {'min': 10, 'max': 15},
        'bom': {'min': 5, 'max': 10},
        'otimo': {'min': 0, 'max': 5},
        'descricao': 'Preço dividido pelo lucro líquido. Mede valuation em relação ao lucro final.',
        'agrupador': 'Valuation',
        'descrcritico': 'P/L negativo reflete lucro líquido negativo, indicando prejuízo. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, com juros de 10-12%, é um sinal de alto risco. Investidores devem evitar, salvo recuperação clara.',
        'descrpessimo': 'Valuation elevado, com P/L acima de 20x, indicando que a ação está sobrevalorizada em relação ao lucro líquido. Comum em empresas de crescimento (ex.: Nubank) ou setores especulativos. Em 2025, reflete otimismo excessivo. Investidores devem exigir forte crescimento do lucro (> 15% ao ano).',
        'descrruim': 'Valuation caro, com P/L entre 15-20x, sugerindo preço elevado em relação ao lucro líquido. Comum em setores com margens moderadas (ex.: saúde, RDOR3). Investidores devem analisar crescimento do lucro e comparar com peers para avaliar se o preço é justificado.',
        'descrmoderado': 'Valuation justo, com P/L entre 10-15x, aceitável para setores com crescimento moderado (ex.: varejo, LREN3). Em 2025, reflete equilíbrio entre preço e lucro líquido. Investidores devem verificar sustentabilidade do lucro e tendências setoriais.',
        'descrbom': 'Valuation atrativo, com P/L entre 5-10x, indicando ação subvalorizada em relação ao lucro líquido. Comum em setores cíclicos em recuperação (ex.: mineração, VALE3). Em 2025, é uma oportunidade, mas exige análise do ciclo econômico e consistência do lucro.',
        'descrotimo': 'Valuation muito atrativo, com P/L entre 0-5x, indicando ação extremamente subvalorizada. Comum em setores com lucros elevados (ex.: siderurgia, GGBR4). Em 2025, é uma oportunidade rara, mas requer confirmação de sustentabilidade do lucro e ausência de riscos ocultos.'
    },
    'Preço sobre Valor Patrimonial (P/VPA)': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': 3, 'max': float('inf')},
        'ruim': {'min': 2, 'max': 3},
        'moderado': {'min': 1, 'max': 2},
        'bom': {'min': 0.5, 'max': 1},
        'otimo': {'min': 0, 'max': 0.5},
        'descricao': 'Preço dividido pelo valor patrimonial por ação. Mede valuation em relação ao patrimônio.',
        'agrupador': 'Valuation',
        'descrcritico': 'P/VPA negativo reflete patrimônio líquido negativo, indicando risco de insolvência. Comum em empresas em crise (ex.: OI, OIBR3). Em 2025, com juros de 10-12%, é um sinal de alto risco. Investidores devem evitar, salvo reestruturação robusta.',
        'descrpessimo': 'Valuation elevado, com P/VPA acima de 3, indicando que a ação está sobrevalorizada em relação ao patrimônio. Comum em empresas de crescimento (ex.: Nubank) ou setores especulativos. Em 2025, reflete otimismo excessivo. Investidores devem exigir forte retorno sobre patrimônio (ROE > 15%).',
        'descrruim': 'Valuation caro, com P/VPA entre 2-3, sugerindo preço elevado em relação ao patrimônio. Comum em setores com margens moderadas (ex.: saúde, RDOR3). Investidores devem analisar ROE e comparar com peers para avaliar se o preço é justificado.',
        'descrmoderado': 'Valuation justo, com P/VPA entre 1-2, aceitável para setores com crescimento moderado (ex.: bancos, ITUB4). Em 2025, reflete equilíbrio entre preço e patrimônio. Investidores devem verificar sustentabilidade do ROE e tendências setoriais.',
        'descrbom': 'Valuation atrativo, com P/VPA entre 0,5-1, indicando ação subvalorizada em relação ao patrimônio. Comum em setores cíclicos em recuperação (ex.: mineração, VALE3). Em 2025, é uma oportunidade, mas exige análise do ciclo econômico e estabilidade do patrimônio.',
        'descrotimo': 'Valuation muito atrativo, com P/VPA entre 0-0,5, indicando ação extremamente subvalorizada. Comum em setores com patrimônio elevado (ex.: siderurgia, GGBR4). Em 2025, é uma oportunidade rara, mas requer confirmação de sustentabilidade do patrimônio e ausência de riscos ocultos.'
    },
    'Patrimônio/Ativos': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 0.2},
        'moderado': {'min': 0.2, 'max': 0.5},
        'bom': {'min': 0.5, 'max': 0.8},
        'otimo': {'min': 0.8, 'max': float('inf')},
        'descricao': 'Patrimônio líquido dividido pelos ativos totais. Mede estrutura de capital.',
        'agrupador': 'Endividamento',
        'descrcritico': 'Patrimônio/Ativos negativo, indicando que os passivos superam os ativos, um sinal de insolvência iminente. Comum em empresas em crise (ex.: OI, OIBR3). Em 2025, reflete alto risco financeiro. Investidores devem evitar, salvo reestruturação robusta.',
        'descrpessimo': 'Patrimônio/Ativos negativo, indicando que os passivos superam os ativos, um sinal de insolvência iminente. Comum em empresas em crise (ex.: OI, OIBR3). Em 2025, reflete alto risco financeiro. Investidores devem evitar, salvo reestruturação robusta.',
        'descrruim': 'Estrutura de capital frágil, com patrimônio representando menos de 20% dos ativos. Comum em empresas com alta alavancagem (ex.: construção, MRVE3). Investidores devem analisar capacidade de geração de caixa e redução de dívidas para avaliar sustentabilidade.',
        'descrmoderado': 'Estrutura de capital razoável, com patrimônio entre 20-50% dos ativos, aceitável para setores com alavancagem moderada (ex.: siderurgia, CSNA3). Em 2025, reflete equilíbrio, mas com riscos. Investidores devem verificar fluxo de caixa livre e gestão de dívidas.',
        'descrbom': 'Estrutura de capital sólida, com patrimônio entre 50-80% dos ativos, indicando baixa alavancagem. Comum em empresas maduras (ex.: utilities, CPFE3). Em 2025, reflete estabilidade financeira. Investidores devem confirmar sustentabilidade do patrimônio.',
        'descrotimo': 'Estrutura de capital excepcional, com patrimônio acima de 80% dos ativos, indicando alta capitalização. Comum em empresas com forte geração de caixa (ex.: mineração, VALE3). Em 2025, reflete robustez financeira, mas deve-se avaliar se excesso de capital indica subinvestimento.'
    },
    'PSR (Preço/Sales Ratio)': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': 4, 'max': float('inf')},
        'ruim': {'min': 3, 'max': 4},
        'moderado': {'min': 1, 'max': 3},
        'bom': {'min': 0.5, 'max': 1},
        'otimo': {'min': 0, 'max': 0.5},
        'descricao': 'Preço dividido pela receita. Mede valuation em relação às vendas.',
        'agrupador': 'Valuation',
        'descrcritico': 'PSR negativo reflete receita negativa, extremamente raro (ex.: OI, OIBR3). Indica falência iminente ou problemas operacionais graves. Em 2025, com juros de 10-12%, é um sinal de alto risco. Investidores devem evitar, salvo recuperação robusta.',
        'descrpessimo': 'Valuation elevado, com PSR acima de 4, indicando que a ação está sobrevalorizada em relação à receita. Comum em empresas de tecnologia (ex.: Nubank) ou setores especulativos. Em 2025, reflete otimismo excessivo. Investidores devem exigir forte crescimento da receita (> 15% ao ano).',
        'descrruim': 'Valuation caro, com PSR entre 3-4, sugerindo preço elevado em relação à receita. Comum em setores com margens moderadas (ex.: saúde, RDOR3). Investidores devem analisar crescimento da receita e comparar com peers para avaliar se o preço é justificado.',
        'descrmoderado': 'Valuation justo, com PSR entre 1-3, aceitável para setores com crescimento moderado (ex.: varejo, LREN3). Em 2025, reflete equilíbrio entre preço e receita. Investidores devem verificar sustentabilidade da receita e tendências setoriais.',
        'descrbom': 'Valuation atrativo, com PSR entre 0,5-1, indicando ação subvalorizada em relação à receita. Comum em setores cíclicos em recuperação (ex.: varejo, CRFB3). Em 2025, é uma oportunidade, mas exige análise do ciclo econômico e estabilidade da receita.',
        'descrotimo': 'Valuation muito atrativo, com PSR entre 0-0,5, indicando ação extremamente subvalorizada. Comum em setores com receitas elevadas (ex.: mineração, VALE3). Em 2025, é uma oportunidade rara, mas requer confirmação de sustentabilidade da receita e ausência de riscos ocultos.'
    },
    'ROA (Retorno sobre Ativos)': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 3},
        'moderado': {'min': 3, 'max': 8},
        'bom': {'min': 8, 'max': 15},
        'otimo': {'min': 15, 'max': float('inf')},
        'descricao': 'Lucro líquido dividido pelos ativos totais. Mede eficiência na utilização de ativos.',
        'agrupador': 'Rentabilidade',
        'descrcritico': 'ROA negativo, indicando prejuízo líquido em relação aos ativos. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, reflete ineficiência grave. Investidores devem evitar, salvo plano de recuperação robusto.',
        'descrpessimo': 'ROA negativo, indicando prejuízo líquido em relação aos ativos. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: varejo, CRFB3). Em 2025, reflete ineficiência grave. Investidores devem evitar, salvo plano de recuperação robusto.',
        'descrruim': 'ROA baixo, entre 0-3%, indicando eficiência limitada na utilização de ativos. Comum em setores intensivos em capital (ex.: energia, CMIG4). Investidores devem analisar estratégias de redução de ativos ociosos e aumento de receita para avaliar potencial de melhoria.',
        'descrmoderado': 'ROA moderado, entre 3-8%, aceitável para setores com operações moderadas (ex.: siderurgia, CSNA3). Em 2025, reflete operação razoável, mas com espaço para melhorias. Investidores devem verificar consistência do lucro e eficiência operacional.',
        'descrbom': 'ROA sólido, entre 8-15%, indicando boa eficiência na utilização de ativos. Comum em setores com operações enxutas (ex.: varejo, LREN3). Em 2025, reflete competitividade. Investidores devem confirmar sustentabilidade do lucro e ausência de ativos ociosos.',
        'descrotimo': 'ROA excepcional, acima de 15%, indicando alta eficiência na utilização de ativos. Comum em setores com margens elevadas (ex.: saúde, RDOR3). Em 2025, reflete liderança operacional. Investidores devem analisar sustentabilidade do lucro e proteção contra concorrência.'
    },
    'ROE (Retorno sobre Patrimônio)': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 5},
        'moderado': {'min': 5, 'max': 15},
        'bom': {'min': 15, 'max': 25},
        'otimo': {'min': 25, 'max': float('inf')},
        'descricao': 'Lucro líquido dividido pelo patrimônio líquido. Mede retorno aos acionistas.',
        'agrupador': 'Rentabilidade',
        'descrcritico': 'ROE negativo, indicando prejuízo líquido em relação ao patrimônio. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: construção, MRVE3). Em 2025, reflete alto risco financeiro. Investidores devem evitar, salvo plano de recuperação robusto.',
        'descrpessimo': 'ROE negativo, indicando prejuízo líquido em relação ao patrimônio. Comum em empresas em crise (ex.: OI, OIBR3) ou setores hipercompetitivos (ex.: construção, MRVE3). Em 2025, reflete alto risco financeiro. Investidores devem evitar, salvo plano de recuperação robusto.',
        'descrruim': 'ROE baixo, entre 0-5%, indicando retorno limitado aos acionistas. Comum em setores com margens apertadas (ex.: construção, MRVE3). Investidores devem analisar estratégias de aumento de lucro e redução de alavancagem para avaliar potencial de melhoria.',
        'descrmoderado': 'ROE moderado, entre 5-15%, aceitável para setores com crescimento moderado (ex.: siderurgia, CSNA3). Em 2025, reflete operação razoável, mas com espaço para melhorias. Investidores devem verificar consistência do lucro e tendências setoriais.',
        'descrbom': 'ROE sólido, entre 15-25%, indicando bom retorno aos acionistas. Comum em setores com barreiras de entrada (ex.: indústria, WEGE3). Em 2025, reflete competitividade. Investidores devem confirmar sustentabilidade do lucro e proteção contra concorrência.',
        'descrotimo': 'ROE excepcional, acima de 25%, indicando alto retorno aos acionistas. Comum em setores de alta margem (ex.: bancos, ITUB4). Em 2025, reflete liderança financeira. Investidores devem analisar sustentabilidade do lucro e proteção contra concorrência.'
    },
    'CAGR Lucros 5 anos': {
        'critico': {'min': float('-inf'), 'max': 0},
        'pessimo': {'min': float('-inf'), 'max': 0},
        'ruim': {'min': 0, 'max': 5},
        'moderado': {'min': 5, 'max': 10},
        'bom': {'min': 10, 'max': 15},
        'otimo': {'min': 15, 'max': float('inf')},
        'descricao': 'Crescimento anual composto do lucro líquido em 5 anos. Mede crescimento sustentável.',
        'agrupador': 'Rentabilidade',
        'descrcritico': 'CAGR negativo, indicando declínio nos lucros líquidos nos últimos 5 anos. Comum em empresas em crise (ex.: OI, OIBR3) ou setores em declínio (ex.: varejo físico, CRFB3). Em 2025, reflete alto risco. Investidores devem evitar, salvo plano de recuperação robusto.',
        'descrpessimo': 'CAGR negativo, indicando declínio nos lucros líquidos nos últimos 5 anos. Comum em empresas em crise (ex.: OI, OIBR3) ou setores em declínio (ex.: varejo físico, CRFB3). Em 2025, reflete alto risco. Investidores devem evitar, salvo plano de recuperação robusto.',
        'descrruim': 'CAGR baixo, entre 0-5%, indicando crescimento estagnado dos lucros. Comum em setores maduros com pouca inovação (ex.: consumo, ABEV3). Investidores devem analisar estratégias de expansão e tendências setoriais para avaliar potencial de melhoria.',
        'descrmoderado': 'CAGR moderado, entre 5-10%, aceitável para setores com crescimento moderado (ex.: siderurgia, CSNA3). Em 2025, reflete operação razoável, mas com espaço para melhorias. Investidores devem verificar sustentabilidade do crescimento e barreiras de entrada.',
        'descrbom': 'CAGR sólido, entre 10-15%, indicando bom crescimento dos lucros. Comum em setores com operações enxutas (ex.: varejo, LREN3). Em 2025, reflete competitividade. Investidores devem confirmar sustentabilidade do crescimento e proteção contra concorrência.',
        'descrotimo': 'CAGR excepcional, acima de 15%, indicando alto crescimento dos lucros. Comum em setores de alta margem (ex.: tecnologia, TOTS3). Em 2025, reflete liderança e inovação. Investidores devem analisar sustentabilidade do crescimento e tendências setoriais.'
    }
}